AWSTemplateFormatVersion: "2010-09-09"
Description: 'sample'
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      # see https://stackoverflow.com/a/76120035
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
